### ISSUE TITLE
lxml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by novoid** [kautsig/ews-orgmode#3]
Hi,

I got an syntax error when I try to run the script the first time:

```
Traceback (most recent call last):
  File "./ews-fetch-calendar.py", line 163, in <module>
    root = etree.fromstring(data)
  File "src/lxml/lxml.etree.pyx", line 3213, in lxml.etree.fromstring (src/lxml/lxml.etree.c:79003)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 646, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105956)
  File "<string>", line 0
lxml.etree.XMLSyntaxError
```

Can you provide the exact version numbers of the libraries used on your side so that I might come up with a virtualenv that uses your setup?

Thanks!

**Comment by kautsig** [comment]
Hi,
are you sure you configured the host, path, etc. correctly? You get an XMLSyntaxError, which means the result from the webservice call cannot be processed. 

There is a debug line in the script, which allows you to dump the response to the console, just uncomment line 2 and 3 and re-execute.

```
# Debug code
# print data
# exit(0)
```

You should then see the xml returned by the webservice. If you see e.g html or similar, you're talking to the wrong endpoint. 
 
In case this really is a dependency issue:
I merged #2 yesterday. The  author claimed to have started with a clean virtualenv, so please check if requirements.txt does the trick for you.

**Comment by novoid** [comment]
I configured my settings in the `config.cfg`.

Before `root = etree.fromstring(data)` I get something in `body` but `data` is empty.

However, I have no clue, what I should put in `path`. So I took the default. Using an empty path leads to the same error. Maybe I need a config file with some more detailed example values?

**Comment by kautsig** [comment]
Just check `config.cfg.sample`, for office 365 i used:

```
host=outlook.office365.com
path=/ews/Exchange.asmx
```

Turns out: when testing i saw the same stack trace you described, when an authentication error happens. In case you're using office356 you have to provide your email address as username (including the domain part).

**Comment by kautsig** [comment]
Closed, because of missing feedback.

**Comment by novoid** [comment]
Sorry for the late feedback.

Error persists when changing username to: `DOMAIN\\first.last` or `DOMAIN\\f.last@example.com` or `DOMAIN\\first.last@example.com` or same without the DOMAIN.

We do have a bit of a chaos in our company. Sometimes usernames are first.last, sometimes f.last, sometimes with domain, sometimes without. Therefore, I have no clue what to use in the config file.

Never mind, I found a different library (exchangelib) which worked for me: https://github.com/novoid/exchange2org
